server:
  error:
    include-message: always
spring:
  data:
    mongodb:
      auto-index-creation: true
      authentication-database: admin
      username: techtutor
      password: password
      database: stores
      port: 27017
      host: localhost
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG